// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmpwxcxlbyfeyidxtewn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcHd4Y3hsYnlmZXlpZHh0ZXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjI1OTUsImV4cCI6MjA3NDAzODU5NX0.8YMxEbhR2XTFzChK1DWjdmGM6KBB9iEUf0s6i4KDUMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});